server {
    listen 80;  # Escucha en el puerto 80
    root /usr/share/nginx/html;  # Indica donde están los archivos que servirá (donde Docker copió /dist)
    index index.html;  # Al ingresar a la raíz del sitio, Nginx sirve index.html

    # Compresión gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;  # Indica qué tipo de archivos comprimirá
    gzip_min_length 1024;  # Solo comprime archivos mayores a 1 KB

    # Caché agresiva (1 año) para assets con hash (JS, CSS, imágenes)
    location ~* \.(js|css|png|jpg|jpeg|svg|ico|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";  # Estos archivos jamás cambiarán con el mismo nombre, si se modifican entonces Vite modificará el hash
    }

    # Security headers
    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "strict-origin-when-cross-origin";

    # SPA fallback: redirigir rutas de React Router a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}